apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pangea-system

resources:
  - external-secrets.yaml
  - postgres-cluster.yaml
  - pangea-namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/name: pangea
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: pangea
    includeSelectors: false
    includeTemplates: true
