//! The Ruby-free variant spec must be as fresh as the canonical one.
//!
//! This repo commits TWO build specs, because `gen` bakes the resolved feature
//! set into a spec and Nix's `rootFeatures` is not honored on the
//! lockfile-builder path — the spec IS the feature decision. The canonical
//! `Cargo.build-spec.json` is gitignored and regenerated by `gen build`; the
//! variant `Cargo.noruby.build-spec.json` is TRACKED and regenerated by
//! `tools/regen-noruby-spec.sh`.
//!
//! ── WHY THIS TEST EXISTS ────────────────────────────────────────────────────
//! The D2 pre-commit tie judges `Cargo.lock` against `Cargo.gen.lock` and knows
//! nothing about the variant. `tools/regen-noruby-spec.sh` says so in its own
//! header — "a stale variant spec is silent" — and then relies on a human
//! remembering to run it whenever `Cargo.lock` moves.
//!
//! That reliance failed. Measured 2026-09-06, from the committed tree:
//!
//!     sha256(Cargo.lock)     = 9b832b37…
//!     Cargo.gen.lock records = 9b832b37…   tie HOLDS  (D2 green)
//!     noruby spec records    = 6440d02e…   tie BROKEN (silent)
//!
//! The variant spec was 11 days stale and still pinned magma 0.1.22 while the
//! lock had moved to 0.1.31. The consequence was not a warning but a hard
//! compile failure, and only in the image nobody builds:
//!
//!     error[E0433]: cannot find `RoutingProviderFactory` in `engine`
//!       --> pangea-operator/src/executor/magma.rs:105
//!
//! ── WHY IT COMPARES TWO RECORDED HASHES RATHER THAN HASHING THE LOCK ───────
//! Hashing `Cargo.lock` here would need a sha256 dependency, and adding one
//! moves `Cargo.lock`, which changes the very hash being checked and forces
//! both specs to be regenerated — a gate that makes work for itself gets
//! deleted. Both files already RECORD the lock hash, and the D2 hook already
//! ties `Cargo.gen.lock` to `Cargo.lock`, so agreement between the two recorded
//! values inherits that guarantee for free.

use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is <root>/pangea-operator.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("manifest dir has a parent")
        .to_path_buf()
}

fn recorded_lock_hash(path: &Path) -> String {
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{} must be present and readable: {e}", path.display()));
    let json: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("{} must be valid JSON: {e}", path.display()));
    json.get("cargo_lock_sha256")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| {
            panic!(
                "{} carries no cargo_lock_sha256 — the freshness tie cannot be \
                 checked, which is worse than a stale spec because it is silent",
                path.display()
            )
        })
        .to_string()
}

#[test]
fn noruby_variant_spec_is_tied_to_the_same_lock_as_the_canonical_one() {
    let root = repo_root();
    let canonical = root.join("Cargo.gen.lock");
    let variant = root.join("Cargo.noruby.build-spec.json");

    let canonical_hash = recorded_lock_hash(&canonical);
    let variant_hash = recorded_lock_hash(&variant);

    assert_eq!(
        canonical_hash, variant_hash,
        "\n\
         The Ruby-free variant spec is STALE.\n\n\
         Cargo.gen.lock records cargo_lock_sha256 = {canonical_hash}\n\
         Cargo.noruby.build-spec.json records     = {variant_hash}\n\n\
         Cargo.lock moved without regenerating the variant. Fix:\n\
         \n\
         \x20   ./tools/regen-noruby-spec.sh\n\
         \n\
         and commit the result. Leaving it stale does not warn — it breaks the\n\
         noruby image build with a type error from whichever dependency the\n\
         variant still pins at an older version, in an image nobody builds\n\
         routinely, so nobody sees it until they do.\n"
    );
}
