//! The Ruby-free variant spec must be as fresh as the canonical one.
//!
//! This repo commits TWO build specs, because `gen` bakes the resolved feature
//! set into a spec and Nix's `rootFeatures` is not honored on the
//! lockfile-builder path — the spec IS the feature decision. The canonical
//! `Cargo.build-spec.json` is gitignored and regenerated by `gen build`; the
//! variant `Cargo.noruby.build-spec.json` is TRACKED and regenerated by
//! `tools/regen-noruby-spec.sh`.
//!
//! ── WHY THIS TEST EXISTS ────────────────────────────────────────────────────
//! The D2 pre-commit tie judges `Cargo.lock` against `Cargo.gen.lock` and knows
//! nothing about the variant. `tools/regen-noruby-spec.sh` says so in its own
//! header — "a stale variant spec is silent" — and then relies on a human
//! remembering to run it whenever `Cargo.lock` moves.
//!
//! That reliance failed. Measured 2026-09-06, from the committed tree:
//!
//!     sha256(Cargo.lock)     = 9b832b37…
//!     Cargo.gen.lock records = 9b832b37…   tie HOLDS  (D2 green)
//!     noruby spec records    = 6440d02e…   tie BROKEN (silent)
//!
//! The variant spec was 11 days stale and still pinned magma 0.1.22 while the
//! lock had moved to 0.1.31. The consequence was not a warning but a hard
//! compile failure, and only in the image nobody builds:
//!
//!     error[E0433]: cannot find `RoutingProviderFactory` in `engine`
//!       --> pangea-operator/src/executor/magma.rs:105
//!
//! ── WHY IT COMPARES TWO RECORDED HASHES RATHER THAN HASHING THE LOCK ───────
//! Hashing `Cargo.lock` here would need a sha256 dependency, and adding one
//! moves `Cargo.lock`, which changes the very hash being checked and forces
//! both specs to be regenerated — a gate that makes work for itself gets
//! deleted. Both files already RECORD the lock hash, and the D2 hook already
//! ties `Cargo.gen.lock` to `Cargo.lock`, so agreement between the two recorded
//! values inherits that guarantee for free.

use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is <root>/pangea-operator.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("manifest dir has a parent")
        .to_path_buf()
}

fn recorded_lock_hash(path: &Path) -> String {
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{} must be present and readable: {e}", path.display()));
    let json: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("{} must be valid JSON: {e}", path.display()));
    json.get("cargo_lock_sha256")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| {
            panic!(
                "{} carries no cargo_lock_sha256 — the freshness tie cannot be \
                 checked, which is worse than a stale spec because it is silent",
                path.display()
            )
        })
        .to_string()
}

/// Every variant spec in the repo, discovered rather than listed.
///
/// ── ★ DISCOVERED, BECAUSE A LIST IS THE BUG THIS GATE EXISTS FOR ──────────
/// The first version of this test named `Cargo.noruby.build-spec.json`
/// explicitly. That reproduces the original defect one level up: adding a THIRD
/// variant — say a Ruby-carrying one — leaves it untied and silently stale,
/// exactly as the second was, and the gate stays green while doing nothing for
/// the new file.
///
/// So the corpus is the filesystem: every `Cargo.<variant>.build-spec.json`
/// beside the canonical lock. A new variant is covered the moment it exists,
/// with no second edit to remember.
fn variant_specs(root: &Path) -> Vec<PathBuf> {
    let mut found: Vec<PathBuf> = std::fs::read_dir(root)
        .expect("repo root is readable")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with("Cargo.") && n.ends_with(".build-spec.json"))
        })
        // The canonical spec is gitignored and regenerated by `gen build`; it is
        // the REFERENCE, not a variant, and comparing it to itself proves
        // nothing.
        .filter(|p| p.file_name().and_then(|n| n.to_str()) != Some("Cargo.build-spec.json"))
        .collect();
    found.sort();
    found
}

#[test]
fn every_variant_spec_is_tied_to_the_same_lock_as_the_canonical_one() {
    let root = repo_root();
    let canonical_hash = recorded_lock_hash(&root.join("Cargo.gen.lock"));

    let variants = variant_specs(&root);
    // Anti-vacuity: with no variants discovered this test would pass while
    // checking nothing, which is precisely how the noruby spec went 11 days
    // stale. The repo has at least one variant by construction.
    assert!(
        !variants.is_empty(),
        "no Cargo.<variant>.build-spec.json found in {} — either the discovery \
         glob broke or the variants were removed; both make this gate vacuous",
        root.display()
    );

    for variant in &variants {
        let variant_hash = recorded_lock_hash(variant);
        assert_eq!(
            canonical_hash, variant_hash,
        "\n\
             A variant build spec is STALE.\n\n\
             variant: {}\n\
             Cargo.gen.lock records cargo_lock_sha256 = {canonical_hash}\n\
             this variant records                     = {variant_hash}\n\n\
             Cargo.lock moved without regenerating it. Fix by re-running the\n\
             generator for THAT variant — e.g. ./tools/regen-noruby-spec.sh —\n\
             and commit the result.\n\n\
             Leaving it stale does not warn. It breaks that variant's build with\n\
             a type error from whichever dependency it still pins at an older\n\
             version, in a build nobody runs routinely, so nobody sees it until\n\
             they do. Measured 2026-09-06: the noruby spec sat 11 days stale at\n\
             magma 0.1.22 against a lock on 0.1.31, and surfaced as\n\
             `E0433: cannot find RoutingProviderFactory`.\n",
            variant.display()
        );
    }
}

/// A variant spec must still carry the feature it exists to deliver.
///
/// ── WHY FRESHNESS IS NOT ENOUGH ─────────────────────────────────────────────
/// The test above proves each variant spec is tied to the current `Cargo.lock`.
/// It says nothing about whether the spec still encodes the FEATURE DECISION
/// that is the entire reason the variant exists — and a spec regenerated with
/// the wrong `--features` line is perfectly fresh and completely wrong.
///
/// That is not hypothetical. `Cargo.ruby.build-spec.json` exists because
/// `rootFeatures` is not honored on the lockfile-builder path, so the variant
/// spec is the ONLY lever that reaches the compiler. Regenerating it with the
/// default feature set would silently produce a second copy of the Ruby-free
/// build under a name promising Ruby — which is precisely the defect the whole
/// variant mechanism was introduced to fix (the `embedded-ruby` image shipped
/// the Ruby-free binary for months on exactly this shape).
///
/// ── COST ──
/// Pure JSON reading, no build, no toolchain. The alternative — building the
/// artifact and asking it via `--capabilities` — is the stronger check and it
/// exists too (flake `checks.x86_64-linux.pangea-operator-ruby-carries-ruby`),
/// but it costs a full libruby-linking compile. This one runs in `cargo test`
/// on every push, so the fast gate catches the common mistake and the slow gate
/// catches everything.
#[test]
fn each_variant_spec_carries_the_feature_that_names_it() {
    let root = repo_root();

    // variant name -> (feature that MUST be present, feature that MUST NOT be)
    // Both directions matter: a `noruby` spec that grew embedded_ruby is just
    // as wrong as a `ruby` spec that lost it, and only checking presence would
    // miss the first entirely.
    let expectations: &[(&str, Option<&str>, Option<&str>)] = &[
        ("Cargo.ruby.build-spec.json", Some("embedded_ruby"), None),
        ("Cargo.noruby.build-spec.json", None, Some("embedded_ruby")),
    ];

    let mut checked = 0usize;
    for (file, must_have, must_not_have) in expectations {
        let path = root.join(file);
        if !path.exists() {
            // A variant that does not exist yet is not a failure — but it is
            // also not evidence, so it must not be counted as one.
            continue;
        }
        let raw = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

        // The spec records resolved features per crate. Rather than walk its
        // shape (which `gen` owns and may restructure), ask the flat question
        // the feature decision actually reduces to: does the string appear as a
        // JSON feature value anywhere in this spec?
        let quoted = |f: &str| format!("\"{f}\"");
        let present = raw.contains(&quoted(must_have.or(*must_not_have).unwrap()));

        if let Some(feature) = must_have {
            assert!(
                present,
                "{file} must carry the `{feature}` feature — that is the only \
                 reason this variant exists, and `rootFeatures` cannot supply it \
                 at build time. Regenerate with the feature ON:\n  \
                 gen build . --features graphql,grpc,executor_magma,{feature} \
                 --out {file}"
            );
        }
        if let Some(feature) = must_not_have {
            assert!(
                !present,
                "{file} carries `{feature}`, which defeats the variant's purpose \
                 — this spec exists to produce a build that CANNOT receive Ruby. \
                 Regenerate with the default feature set."
            );
        }
        checked += 1;
    }

    // ── ANTI-VACUITY ──
    // Every expectation above is skipped when its file is absent, so a rename
    // or a deleted spec would leave this test asserting nothing while passing.
    // The count is the denominator, carried inside the assertion rather than
    // trusted: at least the Ruby-free variant is tracked in git and must exist.
    assert!(
        checked > 0,
        "no variant spec was checked — every expected file is missing. Either \
         the specs were renamed (update `expectations`) or they were deleted \
         (which would silently disable the variant mechanism entirely)."
    );
}
