apiVersion: v1
kind: Service
metadata:
  name: {{ include "pangea-operator.fullname" . }}
  labels:
    {{- include "pangea-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.health }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.ports.graphql }}
      targetPort: graphql
      protocol: TCP
      name: graphql
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "pangea-operator.selectorLabels" . | nindent 4 }}
