//! `TofuPgStateBackend` — a `StateBackend` that reads/writes OpenTofu's
//! **live** `pg`-backend state, so the magma executor shares exactly the
//! state tofu wrote.
//!
//! # Why this exists
//!
//! tofu writes state via its OpenTofu `pg` backend (`backend.tf.json`,
//! generated by `backend/config.rs`): schema `{ns_schema}_{template}_states`,
//! table **`states`** (`id bigint, name text, data text`), row keyed by the
//! workspace `name` (default workspace = `"default"`). Verified against the
//! live rio `pangea_state` DB 2026-05-27 (e.g.
//! `pangea_cloudflare-pleme_cloudflare-pleme_states.states`, default row =
//! 20 resources, serial 2618).
//!
//! The operator's other `StateBackend` impl (`PostgresStateBackend` over
//! `StateStore`) addresses a *different* table (`{ns_schema}.{template}_states`,
//! bytea `data`, with `created_at`) that is unused in production. Routing
//! magma through it would read an empty/absent table → a fleet-wide
//! create-storm (theory/EXECUTOR-MIGRATION.md §VI). This adapter is the
//! bridge: magma reads tofu's real rows, so a magma `plan` matches tofu's
//! plan (the parity gate) and a cut-over does not re-create anything.
//!
//! # Identifier quoting
//!
//! The schema name embeds namespace + template names, which contain
//! hyphens (`pangea_cloudflare-pleme_cloudflare-pleme_states`), so it MUST
//! be a double-quoted SQL identifier. Inputs are k8s object names
//! (`[a-z0-9.-]`), but we defensively double any embedded `"`.
//!
//! # Data column is TEXT
//!
//! OpenTofu stores the state JSON in a `text` column (not `bytea`). We read
//! it as `String` and expose `Vec<u8>` (UTF-8 JSON) to match the
//! `StateBackend` contract; we write `&str`.

use crate::backend::state::{StateEntry, TerraformState};
use crate::backend::state_backend::StateBackend;
use crate::error::{Error, Result};

use async_trait::async_trait;
use chrono::Utc;
use sqlx::PgPool;
use std::sync::Arc;
use tracing::{debug, info};

/// `StateBackend` over OpenTofu's live `pg`-backend `states` table.
pub struct TofuPgStateBackend {
    pool: Arc<PgPool>,
}

impl TofuPgStateBackend {
    pub fn new(pool: Arc<PgPool>) -> Self {
        Self { pool }
    }

    /// `"{schema}_{template}_states".states` — the OpenTofu pg-backend
    /// table. The schema is double-quoted (it contains hyphens); the
    /// `states` table name is a fixed, safe identifier.
    fn states_table(schema_name: &str, template_name: &str) -> String {
        let schema = format!("{schema_name}_{template_name}_states");
        // Defensive: double any embedded quote so the identifier stays
        // well-formed even for unexpected input.
        let quoted = schema.replace('"', "\"\"");
        format!("\"{quoted}\".states")
    }
}

/// Postgres SQLSTATE for `undefined_table` — raised by a `SELECT` against a
/// schema/table that does not exist.
const UNDEFINED_TABLE: &str = "42P01";

/// Does this SQLSTATE mean "the relation does not exist"?
///
/// Pure + testable; the call sites extract the code from the live
/// `sqlx::Error`. OpenTofu's `pg` backend creates the
/// `{schema}_{template}_states` schema + `states` table lazily on the first
/// *write*. A template that has never applied — every `autoApprove: false`
/// plan-only adoption, which is the canonical "state-match existing infra"
/// entry point — therefore has no such table yet. A READ against it returns
/// `42P01`, which means **no state persisted** (a fresh workspace), NOT a
/// hard failure. Mapping it to an empty result honors the `StateBackend`
/// contract (`Ok(None)` = fresh workspace) and lets a plan-only reconcile
/// surface its diff instead of wedging in `Failed`.
fn sqlstate_is_undefined_table(code: Option<&str>) -> bool {
    code == Some(UNDEFINED_TABLE)
}

/// `true` when a `sqlx::Error` is a Postgres `undefined_table` (42P01).
fn is_undefined_table(e: &sqlx::Error) -> bool {
    sqlstate_is_undefined_table(e.as_database_error().and_then(|d| d.code()).as_deref())
}

#[async_trait]
impl StateBackend for TofuPgStateBackend {
    async fn get_state(
        &self,
        schema_name: &str,
        template_name: &str,
        state_name: &str,
    ) -> Result<Option<StateEntry>> {
        let table = Self::states_table(schema_name, template_name);
        // `data` is TEXT in the OpenTofu pg backend; read as String.
        let query = format!("SELECT id, name, data FROM {table} WHERE name = $1 LIMIT 1");

        let row: Option<(i64, String, Option<String>)> = match sqlx::query_as(&query)
            .bind(state_name)
            .fetch_optional(self.pool.as_ref())
            .await
        {
            Ok(r) => r,
            // The state table is created lazily on first apply; a never-applied
            // (plan-only) template has none yet → that is "no state", not an error.
            Err(e) if is_undefined_table(&e) => {
                debug!(table, "state table absent (never applied) — treating as no state");
                return Ok(None);
            }
            Err(e) => return Err(Error::Database(e)),
        };

        Ok(row.map(|(id, name, data)| StateEntry {
            id,
            name,
            data: data.map(String::into_bytes),
            // OpenTofu's `states` table has no created_at column; synthesize.
            created_at: Utc::now(),
        }))
    }

    async fn get_parsed_state(
        &self,
        schema_name: &str,
        template_name: &str,
        state_name: &str,
    ) -> Result<Option<TerraformState>> {
        match self.get_state(schema_name, template_name, state_name).await? {
            Some(e) if e.data.is_some() => {
                let data = e.data.unwrap();
                let state: TerraformState =
                    serde_json::from_slice(&data).map_err(Error::Serialization)?;
                Ok(Some(state))
            }
            _ => Ok(None),
        }
    }

    async fn save_state(
        &self,
        schema_name: &str,
        template_name: &str,
        state_name: &str,
        data: &[u8],
    ) -> Result<i64> {
        let table = Self::states_table(schema_name, template_name);
        // The state JSON is UTF-8; bind as &str into the TEXT column.
        let text = std::str::from_utf8(data)
            .map_err(|e| Error::Config(format!("state bytes are not valid UTF-8: {e}")))?;

        debug!(table, state_name, data_size = data.len(), "magma: saving tofu-format state");

        let query = format!(
            "INSERT INTO {table} (name, data) VALUES ($1, $2) \
             ON CONFLICT (name) DO UPDATE SET data = EXCLUDED.data \
             RETURNING id"
        );

        let row: (i64,) = sqlx::query_as(&query)
            .bind(state_name)
            .bind(text)
            .fetch_one(self.pool.as_ref())
            .await
            .map_err(Error::Database)?;

        info!(table, state_name, id = row.0, "magma: state saved");
        Ok(row.0)
    }

    async fn delete_state(
        &self,
        schema_name: &str,
        template_name: &str,
        state_name: &str,
    ) -> Result<bool> {
        let table = Self::states_table(schema_name, template_name);
        let query = format!("DELETE FROM {table} WHERE name = $1");
        let result = sqlx::query(&query)
            .bind(state_name)
            .execute(self.pool.as_ref())
            .await
            .map_err(Error::Database)?;
        Ok(result.rows_affected() > 0)
    }

    async fn list_states(
        &self,
        schema_name: &str,
        template_name: &str,
    ) -> Result<Vec<StateEntry>> {
        let table = Self::states_table(schema_name, template_name);
        let query = format!("SELECT id, name, data FROM {table} ORDER BY id DESC");
        let rows: Vec<(i64, String, Option<String>)> = match sqlx::query_as(&query)
            .fetch_all(self.pool.as_ref())
            .await
        {
            Ok(r) => r,
            // Never-applied template → no state table yet → empty list, not an error.
            Err(e) if is_undefined_table(&e) => {
                debug!(table, "state table absent (never applied) — no states to list");
                return Ok(vec![]);
            }
            Err(e) => return Err(Error::Database(e)),
        };
        Ok(rows
            .into_iter()
            .map(|(id, name, data)| StateEntry {
                id,
                name,
                data: data.map(String::into_bytes),
                created_at: Utc::now(),
            })
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn states_table_matches_opentofu_pg_layout() {
        // Verified live: pangea_cloudflare-pleme_cloudflare-pleme_states.states
        assert_eq!(
            TofuPgStateBackend::states_table("pangea_cloudflare-pleme", "cloudflare-pleme"),
            "\"pangea_cloudflare-pleme_cloudflare-pleme_states\".states"
        );
        // rio-architectures shared namespace
        assert_eq!(
            TofuPgStateBackend::states_table("pangea_rio-infra", "rio-zot-cloudflare-tunnel"),
            "\"pangea_rio-infra_rio-zot-cloudflare-tunnel_states\".states"
        );
    }

    #[test]
    fn embedded_quote_is_doubled() {
        // Defensive identifier hygiene — a stray quote can't break out.
        let t = TofuPgStateBackend::states_table("pangea_x\"y", "t");
        assert_eq!(t, "\"pangea_x\"\"y_t_states\".states");
        assert!(!t.contains("x\"y"), "raw quote must be escaped");
    }

    #[test]
    fn undefined_table_sqlstate_is_recognized_as_no_state() {
        // 42P01 (undefined_table) on a READ must be treated as "no state yet"
        // — the never-applied plan-only adoption path. Regression for the
        // akeyless-dev canary: a missing state table wedged the reconcile in
        // Failed ("relation … does not exist") instead of surfacing the plan.
        assert!(sqlstate_is_undefined_table(Some(UNDEFINED_TABLE)));
        assert!(sqlstate_is_undefined_table(Some("42P01")));
    }

    #[test]
    fn other_sqlstates_still_propagate_as_errors() {
        // Only undefined_table is swallowed; every other DB error must surface
        // (we never want to silently treat a real failure as empty state).
        assert!(!sqlstate_is_undefined_table(None));
        assert!(!sqlstate_is_undefined_table(Some("42501"))); // insufficient_privilege
        assert!(!sqlstate_is_undefined_table(Some("08006"))); // connection_failure
        assert!(!sqlstate_is_undefined_table(Some("23505"))); // unique_violation
        assert!(!sqlstate_is_undefined_table(Some("")));
    }
}
