#!/usr/bin/env python3
"""
check-crd-drift.py — the CRD generation forcing-function.

Asserts that the helmworks chart's pangea-operator CRDs are byte-for-spec
identical to what the operator's own `--generate-crds` produces from its Rust
structs. This closes the generation border that caused the 2026-06-16 ~2-day
outage and the dashboard-as-code activation cascade: a struct field was added
in Rust (e.g. ArchitectureGem.dependencies) but the shipped chart CRD was never
regenerated, so the apiserver silently pruned the field.

It is the GEN TYPED-SPEC CONTRACT applied to operator CRDs: a stale generated
artifact is a CI failure, not a runtime failure.

We compare each CRD's `.spec` (the struct-derived schema: group / names / scope /
versions+openAPIV3Schema). Chart-injected `.metadata` (labels, the
`helm.sh/resource-policy: keep` annotation the generator doesn't emit) is
deliberately ignored — only the typed-source-derived schema must match.

A ratchet: a baseline file lists CRDs with KNOWN pre-existing drift (tracked
tech debt — print a warning, don't fail). Drift in ANY other CRD fails the
build. Remove a name from the baseline as you regenerate+sync it, and it can
never silently drift again.

Usage:
    check-crd-drift.py <generated-all-crds.yaml> <helmworks-chart-crds-dir> [baseline-file]
Exit 0 = in sync (or only baselined drift); exit 1 = NEW drift.
"""
import sys
import glob
import os

try:
    import yaml
except ImportError:
    print("FATAL: PyYAML required (nix-shell -p python3Packages.pyyaml, or pip install pyyaml)")
    sys.exit(2)


def load_crds(path):
    """name -> CRD doc, for every CustomResourceDefinition in a YAML file."""
    out = {}
    with open(path) as f:
        for d in yaml.safe_load_all(f):
            if isinstance(d, dict) and d.get("kind") == "CustomResourceDefinition":
                out[d["metadata"]["name"]] = d
    return out


def load_baseline(path):
    """Set of CRD names with known, tracked pre-existing drift (lines; '#' comments)."""
    if not path or not os.path.exists(path):
        return set()
    names = set()
    with open(path) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if line:
                names.add(line)
    return names


def main():
    if len(sys.argv) not in (3, 4):
        print(__doc__)
        sys.exit(2)
    generated_file, chart_dir = sys.argv[1], sys.argv[2]
    baseline = load_baseline(sys.argv[3] if len(sys.argv) == 4 else None)

    gen = load_crds(generated_file)
    chart = {}
    for f in sorted(glob.glob(os.path.join(chart_dir, "*.yaml"))):
        for name, doc in load_crds(f).items():
            chart[name] = (doc, os.path.basename(f))

    drift = []  # (crd_name, message)

    # 1. every generated CRD must exist in the chart with a matching spec
    for name, gdoc in sorted(gen.items()):
        if name not in chart:
            drift.append((name, f"{name}: generated by the operator but MISSING from the chart crds/"))
            continue
        cdoc, fname = chart[name]
        if gdoc.get("spec") != cdoc.get("spec"):
            drift.append((name, f"{name}: chart {fname} .spec DIFFERS from `--generate-crds` "
                                f"(the Rust struct changed but the chart CRD was not regenerated)"))

    # 2. no orphan chart CRDs the operator no longer generates
    for name, (cdoc, fname) in sorted(chart.items()):
        if name not in gen:
            drift.append((name, f"{name}: chart {fname} is NOT produced by `--generate-crds` (orphan CRD)"))

    new_drift = [(n, m) for (n, m) in drift if n not in baseline]
    baselined = [(n, m) for (n, m) in drift if n in baseline]

    if baselined:
        print("⚠ KNOWN drift (baselined — tracked tech debt, regenerate+sync to clear):")
        for _, m in baselined:
            print(f"    {m}")
        print()

    if new_drift:
        print("CRD DRIFT — chart CRDs are out of sync with the operator's Rust structs:\n")
        for _, m in new_drift:
            print(f"  ✗ {m}")
        print(
            "\nFix: regenerate (pangea-operator/CLAUDE.md §Generating CRDs):\n"
            "  nix develop .#ruby-eval -c cargo run -p pangea-operator --bin pangea-operator \\\n"
            "    --no-default-features -- --generate-crds > /tmp/all-crds.yaml\n"
            "split per-CRD, overwrite helmworks/charts/pangea-operator/crds/<name>.yaml, bump\n"
            "the chart Chart.yaml — and confirm the CRD change is ADDITIVE before it ships\n"
            "(CreateReplace prunes any removed field from live CRs)."
        )
        sys.exit(1)

    n_ok = len(gen) - len(baselined)
    print(f"OK: {n_ok}/{len(gen)} CRDs match `--generate-crds`"
          + (f"; {len(baselined)} baselined (tracked)." if baselined else " (no drift)."))
    sys.exit(0)


if __name__ == "__main__":
    main()
